export const MEDICINES_DB = [
    { name: "Metformin", dose: "500mg", type: "Diabetes", cost: "₹150", generic: "Glycomet" },
    { name: "Atorvastatin", dose: "20mg", type: "Cholesterol", cost: "₹240", generic: "Lipitor" },
    { name: "Amoxicillin", dose: "500mg", type: "Antibiotic", cost: "₹80", generic: "Mox" },
    { name: "Lisinopril", dose: "10mg", type: "Blood Pressure", cost: "₹120", generic: "Listril" },
    { name: "Amlodipine", dose: "5mg", type: "Blood Pressure", cost: "₹60", generic: "Amlokind" },
    { name: "Omeprazole", dose: "20mg", type: "Acidity", cost: "₹45", generic: "Omez" },
    { name: "Paracetamol", dose: "650mg", type: "Fever/Pain", cost: "₹30", generic: "Dolo 650" },
    { name: "Azithromycin", dose: "500mg", type: "Antibiotic", cost: "₹110", generic: "Azithral" },
    { name: "Losartan", dose: "50mg", type: "Blood Pressure", cost: "₹95", generic: "Losar" },
    { name: "Levothyroxine", dose: "50mcg", type: "Thyroid", cost: "₹140", generic: "Thyronorm" },
    { name: "Telmisartan", dose: "40mg", type: "Blood Pressure", cost: "₹130", generic: "Telma" },
    { name: "Metoprolol", dose: "25mg", type: "Heart Rate", cost: "₹85", generic: "Metolar" },
    { name: "Pantoprazole", dose: "40mg", type: "Acidity", cost: "₹70", generic: "Pan 40" },
    { name: "Montelukast", dose: "10mg", type: "Asthma/Allergy", cost: "₹160", generic: "Montair" },
    { name: "Rosuvastatin", dose: "10mg", type: "Cholesterol", cost: "₹210", generic: "Rosuvas" },
    { name: "Glimepiride", dose: "2mg", type: "Diabetes", cost: "₹90", generic: "Amaryl" },
    { name: "Cetirizine", dose: "10mg", type: "Allergy", cost: "₹25", generic: "Okacet" },
    { name: "Ibuprofen", dose: "400mg", type: "Pain Relief", cost: "₹40", generic: "Brufen" },
    { name: "Diclofenac", dose: "50mg", type: "Pain Relief", cost: "₹35", generic: "Voveran" },
    { name: "Ciprofloxacin", dose: "500mg", type: "Antibiotic", cost: "₹75", generic: "Ciplox" },
    { name: "Sitagliptin", dose: "100mg", type: "Diabetes", cost: "₹450", generic: "Januvia" },
    { name: "Vildagliptin", dose: "50mg", type: "Diabetes", cost: "₹320", generic: "Galvus" },
    { name: "Clopidogrel", dose: "75mg", type: "Blood Thinner", cost: "₹180", generic: "Clopilet" },
    { name: "Aspirin", dose: "75mg", type: "Blood Thinner", cost: "₹20", generic: "Ecosprin" },
    { name: "Spironolactone", dose: "25mg", type: "Diuretic", cost: "₹65", generic: "Aldactone" },
    { name: "Furosemide", dose: "40mg", type: "Diuretic", cost: "₹15", generic: "Lasix" },
    { name: "Ramipril", dose: "5mg", type: "Blood Pressure", cost: "₹80", generic: "Cardace" },
    { name: "Bisoprolol", dose: "5mg", type: "Heart Rate", cost: "₹110", generic: "Concor" },
    { name: "Teneligliptin", dose: "20mg", type: "Diabetes", cost: "₹140", generic: "Zita Plus" },
    { name: "Empagliflozin", dose: "10mg", type: "Diabetes", cost: "₹550", generic: "Jardiance" },
    { name: "Dapagliflozin", dose: "10mg", type: "Diabetes", cost: "₹580", generic: "Forxiga" },
    { name: "Sitagliptin + Metformin", dose: "50/500mg", type: "Diabetes", cost: "₹380", generic: "Janumet" },
    { name: "Voglibose", dose: "0.3mg", type: "Diabetes", cost: "₹120", generic: "Voglibite" },
    { name: "Pioglitazone", dose: "15mg", type: "Diabetes", cost: "₹85", generic: "Pioz" },
    { name: "Rabeprazole", dose: "20mg", type: "Acidity", cost: "₹95", generic: "Cyra" },
    { name: "Domperidone", dose: "10mg", type: "Anti-emetic", cost: "₹40", generic: "Domstal" },
    { name: "Itopride", dose: "50mg", type: "Digestion", cost: "₹150", generic: "Ganaton" },
    { name: "Levosulpiride", dose: "25mg", type: "Digestion/Mental", cost: "₹180", generic: "Lesuride" },
    { name: "Fluoxetine", dose: "20mg", type: "Antidepressant", cost: "₹70", generic: "Fludac" },
    { name: "Sertraline", dose: "50mg", type: "Antidepressant", cost: "₹130", generic: "Sertra" },
    { name: "Escitalopram", dose: "10mg", type: "Antidepressant", cost: "₹110", generic: "Nexito" },
    { name: "Paroxetine", dose: "20mg", type: "Antidepressant", cost: "₹190", generic: "Paxidep" },
    { name: "Clonazepam", dose: "0.5mg", type: "Anxiety", cost: "₹60", generic: "Zapiz" },
    { name: "Alprazolam", dose: "0.25mg", type: "Anxiety", cost: "₹40", generic: "Alprax" },
    { name: "Etizolam", dose: "0.5mg", type: "Anxiety", cost: "₹80", generic: "Etilaam" },
    { name: "Lorazepam", dose: "1mg", type: "Anxiety", cost: "₹30", generic: "Ativan" },
    { name: "Pregabalin", dose: "75mg", type: "Nerve Pain", cost: "₹220", generic: "Lyrica" },
    { name: "Gabapentin", dose: "300mg", type: "Nerve Pain", cost: "₹250", generic: "Gabapin" },
    { name: "Methylcobalamin", dose: "1500mcg", type: "Vitamin B12", cost: "₹120", generic: "Me-12" },
    { name: "Vitamin D3", dose: "60K IU", type: "Vitamin D", cost: "₹180", generic: "Calcirol" },
    { name: "Calcium + Vit D3", dose: "500mg", type: "Supplements", cost: "₹90", generic: "Shelcal" },
    { name: "Iron + Folic Acid", dose: "100mg", type: "Supplements", cost: "₹110", generic: "Dexorange" },
    { name: "Multivitamin", dose: "1 Cap", type: "Supplements", cost: "₹150", generic: "Revital" },
    { name: "Finasteride", dose: "1mg", type: "Hair Loss", cost: "₹280", generic: "Finpecia" },
    { name: "Minoxidil", dose: "5% Sol", type: "Hair Loss", cost: "₹650", generic: "Mintop" },
    { name: "Tretinoin", dose: "0.025%", type: "Acne", cost: "₹210", generic: "Retino-A" },
    { name: "Adapalene", dose: "0.1%", type: "Acne", cost: "₹240", generic: "Adaferin" },
    { name: "Clindamycin", dose: "1% Gel", type: "Acne", cost: "₹130", generic: "Clindac-A" },
    { name: "Mupirocin", dose: "2% Oint", type: "Antiseptic", cost: "₹180", generic: "T-Bact" },
    { name: "Fucidin", dose: "2% Cream", type: "Antibiotic", cost: "₹150", generic: "Fucidin" },
    { name: "Salbutamol", dose: "2mg", type: "Asthma", cost: "₹20", generic: "Asthalin" },
    { name: "Levosalbutamol", dose: "1.25mg", type: "Asthma", cost: "₹45", generic: "Levolin" },
    { name: "Budesonide", dose: "200mcg", type: "Inhaler", cost: "₹350", generic: "Budecort" },
    { name: "Fluticasone", dose: "125mcg", type: "Inhaler", cost: "₹480", generic: "Flohale" },
    { name: "Tiotropium", dose: "18mcg", type: "COPD", cost: "₹550", generic: "Tiova" },
    { name: "Doxofylline", dose: "400mg", type: "Asthma", cost: "₹140", generic: "Doxiflo" },
    { name: "Aceclofenac", dose: "100mg", type: "Pain Relief", cost: "₹65", generic: "Zerodol" },
    { name: "Tramadol", dose: "50mg", type: "Pain Relief", cost: "₹90", generic: "Ultracet" },
    { name: "Meftal Spas", dose: "1 Tab", type: "Pain Relief", cost: "₹50", generic: "Mefenamic Acid" },
    { name: "Combiflam", dose: "1 Tab", type: "Pain Relief", cost: "₹45", generic: "Ibu+Para" },
    { name: "Sumatriptan", dose: "50mg", type: "Migraine", cost: "₹120", generic: "Suminat" },
    { name: "Naproxen", dose: "250mg", type: "Pain Relief", cost: "₹85", generic: "Naprosyn" },
    { name: "Propranolol", dose: "10mg", type: "Migraine/BP", cost: "₹40", generic: "Inderal" },
    { name: "Domperidone + Pantoprazole", dose: "30/40mg", type: "Acidity", cost: "₹220", generic: "Pantocid D" },
    { name: "Levocetirizine", dose: "5mg", type: "Allergy", cost: "₹60", generic: "Levocet" },
    { name: "Fexofenadine", dose: "120mg", type: "Allergy", cost: "₹180", generic: "Allegra" },
    { name: "Loratadine", dose: "10mg", type: "Allergy", cost: "₹70", generic: "Lorfast" },
    { name: "Hydroxyzine", dose: "25mg", type: "Allergy/Anxiety", cost: "₹90", generic: "Atarax" },
    { name: "Doxycycline", dose: "100mg", type: "Antibiotic", cost: "₹120", generic: "Doxiv" },
    { name: "Metronidazole", dose: "400mg", type: "Antibiotic", cost: "₹40", generic: "Flagyl" },
    { name: "Albendazole", dose: "400mg", type: "Deworming", cost: "₹25", generic: "Zentel" },
    { name: "Ofloxacin", dose: "200mg", type: "Antibiotic", cost: "₹85", generic: "Zenflox" },
    { name: "Levofloxacin", dose: "500mg", type: "Antibiotic", cost: "₹110", generic: "Loxof" },
    { name: "Cefixime", dose: "200mg", type: "Antibiotic", cost: "₹150", generic: "Taxim-O" },
    { name: "Cefpodoxime", dose: "200mg", type: "Antibiotic", cost: "₹240", generic: "Gudcef" },
    { name: "Linezolid", dose: "600mg", type: "Antibiotic", cost: "₹450", generic: "Lizomac" },
    { name: "Warfarin", dose: "5mg", type: "Blood Thinner", cost: "₹95", generic: "Uniwarfare" },
    { name: "Dabigatran", dose: "110mg", type: "Blood Thinner", cost: "₹650", generic: "Pradaxa" },
    { name: "Rivaroxaban", dose: "10mg", type: "Blood Thinner", cost: "₹780", generic: "Xarelto" },
    { name: "Digoxin", dose: "0.25mg", type: "Heart Failure", cost: "₹35", generic: "Lanoxin" },
    { name: "Isosorbide Dinitrate", dose: "10mg", type: "Angina", cost: "₹25", generic: "Sorbitrate" },
    { name: "Sildenafil", dose: "50mg", type: "Erectile Dysfunction", cost: "₹350", generic: "Viagra" },
    { name: "Tadalafil", dose: "20mg", type: "Erectile Dysfunction", cost: "₹420", generic: "Cialis" },
    { name: "Nitrofurantoin", dose: "100mg", type: "UTI", cost: "₹180", generic: "Niftran" },
    { name: "Fluconazole", dose: "150mg", type: "Antifungal", cost: "₹40", generic: "Forcan" },
    { name: "Itraconazole", dose: "100mg", type: "Antifungal", cost: "₹320", generic: "Canditral" },
    { name: "Terbinafine", dose: "250mg", type: "Antifungal", cost: "₹280", generic: "Sebifin" },
    { name: "Ketoconazole", dose: "2% Cream", type: "Antifungal", cost: "₹160", generic: "Nizoral" },
    { name: "Aciclovir", dose: "400mg", type: "Antiviral", cost: "₹140", generic: "Zovirax" },
    { name: "Oseltamivir", dose: "75mg", type: "Antiviral", cost: "₹650", generic: "Antiflu" },
    // --- 100 New Medicines Added Below ---
    { name: "Valsartan", dose: "80mg", type: "Blood Pressure", cost: "₹150", generic: "Valzaar" },
    { name: "Glipizide", dose: "5mg", type: "Diabetes", cost: "₹45", generic: "Glynase" },
    { name: "Duloxetine", dose: "30mg", type: "Antidepressant", cost: "₹160", generic: "Symbalta" },
    { name: "Venlafaxine", dose: "75mg", type: "Antidepressant", cost: "₹180", generic: "Effexor" },
    { name: "Tamsulosin", dose: "0.4mg", type: "Prostate", cost: "₹140", generic: "Veltam" },
    { name: "Silodosin", dose: "8mg", type: "Prostate", cost: "₹240", generic: "Silodal" },
    { name: "Dutasteride", dose: "0.5mg", type: "Prostate", cost: "₹210", generic: "Dutas" },
    { name: "Allopurinol", dose: "100mg", type: "Gout", cost: "₹40", generic: "Zyloric" },
    { name: "Febuxostat", dose: "40mg", type: "Gout", cost: "₹180", generic: "Febutaz" },
    { name: "Latanoprost", dose: "0.005%", type: "Glaucoma", cost: "₹350", generic: "Xalatan" },
    { name: "Bimatoprost", dose: "0.01%", type: "Glaucoma", cost: "₹420", generic: "Careprost" },
    { name: "Timolol", dose: "0.5%", type: "Glaucoma", cost: "₹80", generic: "Glucomol" },
    { name: "Brimonidine", dose: "0.15%", type: "Glaucoma", cost: "₹250", generic: "Alphagan" },
    { name: "Clarithromycin", dose: "500mg", type: "Antibiotic", cost: "₹220", generic: "Claribid" },
    { name: "Amoxyclav", dose: "625mg", type: "Antibiotic", cost: "₹160", generic: "Augmentin" },
    { name: "Cefuroxime", dose: "500mg", type: "Antibiotic", cost: "₹280", generic: "Ceftum" },
    { name: "Erythromycin", dose: "500mg", type: "Antibiotic", cost: "₹80", generic: "Althrocin" },
    { name: "Acyclovir", dose: "800mg", type: "Antiviral", cost: "₹250", generic: "Herperax" },
    { name: "Mebendazole", dose: "100mg", type: "Deworming", cost: "₹30", generic: "Mebex" },
    { name: "Ivermectin", dose: "12mg", type: "Anti-parasitic", cost: "₹50", generic: "Ivecop" },
    { name: "Loperamide", dose: "2mg", type: "Diarrhea", cost: "₹20", generic: "Imodium" },
    { name: "Racecadotril", dose: "100mg", type: "Diarrhea", cost: "₹110", generic: "Zedott" },
    { name: "Ondansetron", dose: "4mg", type: "Anti-emetic", cost: "₹45", generic: "Emeset" },
    { name: "Prochlorperazine", dose: "5mg", type: "Vertigo/Nausea", cost: "₹35", generic: "Stemetil" },
    { name: "Betahistine", dose: "16mg", type: "Vertigo", cost: "₹120", generic: "Vertin" },
    { name: "Cinnarizine", dose: "25mg", type: "Vertigo", cost: "₹80", generic: "Stugeron" },
    { name: "Amitriptyline", dose: "25mg", type: "Depression/Pain", cost: "₹50", generic: "Tryptomer" },
    { name: "Nortriptyline", dose: "25mg", type: "Nerve Pain", cost: "₹85", generic: "Sensival" },
    { name: "Haloperidol", dose: "5mg", type: "Antipsychotic", cost: "₹40", generic: "Serenace" },
    { name: "Olanzapine", dose: "5mg", type: "Antipsychotic", cost: "₹65", generic: "Oleanz" },
    { name: "Risperidone", dose: "2mg", type: "Antipsychotic", cost: "₹50", generic: "Sizodon" },
    { name: "Quetiapine", dose: "50mg", type: "Antipsychotic", cost: "₹120", generic: "Qutan" },
    { name: "Chlorpromazine", dose: "100mg", type: "Antipsychotic", cost: "₹50", generic: "Largactil" },
    { name: "Lithium", dose: "300mg", type: "Bipolar", cost: "₹75", generic: "Lithosun" },
    { name: "Phenytoin", dose: "100mg", type: "Epilepsy", cost: "₹35", generic: "Eptoin" },
    { name: "Carbamazepine", dose: "200mg", type: "Epilepsy", cost: "₹45", generic: "Tegrital" },
    { name: "Valproate", dose: "500mg", type: "Epilepsy", cost: "₹140", generic: "Encorate" },
    { name: "Levetiracetam", dose: "500mg", type: "Epilepsy", cost: "₹220", generic: "Keppra" },
    { name: "Oxcarbazepine", dose: "300mg", type: "Epilepsy", cost: "₹180", generic: "Oxetol" },
    { name: "Ursodeoxycholic Acid", dose: "300mg", type: "Gallstones", cost: "₹320", generic: "Udyliv" },
    { name: "Mebeverine", dose: "200mg", type: "IBS", cost: "₹210", generic: "Colospa" },
    { name: "Drotavarine", dose: "80mg", type: "Spasm", cost: "₹65", generic: "Drotin" },
    { name: "Hyoscine", dose: "10mg", type: "Spasm", cost: "₹80", generic: "Buscopan" },
    { name: "Simethicone", dose: "40mg", type: "Gas", cost: "₹50", generic: "Gastica" },
    { name: "Lactulose", dose: "10g", type: "Constipation", cost: "₹180", generic: "Duphalac" },
    { name: "Bisacodyl", dose: "5mg", type: "Constipation", cost: "₹25", generic: "Dulcolax" },
    { name: "Psyllium Husk", dose: "5g", type: "Constipation", cost: "₹120", generic: "Isabgol" },
    { name: "Sucralfate", dose: "1g", type: "Ulcer", cost: "₹160", generic: "Sucrafil" },
    { name: "Misoprostol", dose: "200mcg", type: "Ulcer", cost: "₹140", generic: "Cytolog" },
    { name: "Ranitidine", dose: "150mg", type: "Acidity", cost: "₹15", generic: "Rantac" },
    { name: "Famotidine", dose: "40mg", type: "Acidity", cost: "₹30", generic: "Famon" },
    { name: "Esomeprazole", dose: "40mg", type: "Acidity", cost: "₹110", generic: "Nexpro" },
    { name: "Lansoprazole", dose: "30mg", type: "Acidity", cost: "₹65", generic: "Lanzol" },
    { name: "Glucagon", dose: "1mg", type: "Hypoglycemia", cost: "₹1200", generic: "Glucagon Kit" },
    { name: "Insulin Glargine", dose: "100IU", type: "Diabetes", cost: "₹850", generic: "Lantus" },
    { name: "Insulin Aspart", dose: "100IU", type: "Diabetes", cost: "₹720", generic: "Novorapid" },
    { name: "Acarbose", dose: "50mg", type: "Diabetes", cost: "₹95", generic: "Glucobay" },
    { name: "Linagliptin", dose: "5mg", type: "Diabetes", cost: "₹280", generic: "Trajenta" },
    { name: "Pravastatin", dose: "40mg", type: "Cholesterol", cost: "₹190", generic: "Pravator" },
    { name: "Fluvastatin", dose: "40mg", type: "Cholesterol", cost: "₹250", generic: "Lescol" },
    { name: "Ezetimibe", dose: "10mg", type: "Cholesterol", cost: "₹140", generic: "Zetia" },
    { name: "Fenofibrate", dose: "160mg", type: "Triglycerides", cost: "₹160", generic: "Lipicard" },
    { name: "Niacin", dose: "500mg", type: "Cholesterol", cost: "₹90", generic: "Niaspan" },
    { name: "Captopril", dose: "25mg", type: "Blood Pressure", cost: "₹65", generic: "Aceten" },
    { name: "Enalapril", dose: "5mg", type: "Blood Pressure", cost: "₹45", generic: "Envas" },
    { name: "Nebivolol", dose: "5mg", type: "Heart Rate", cost: "₹110", generic: "Nebistar" },
    { name: "Carvedilol", dose: "12.5mg", type: "Heart Rate", cost: "₹75", generic: "Carloc" },
    { name: "Verapamil", dose: "40mg", type: "Blood Pressure/Heart", cost: "₹40", generic: "Calaptin" },
    { name: "Diltiazem", dose: "90mg", type: "Blood Pressure/Heart", cost: "₹85", generic: "Dilzem" },
    { name: "Nifedipine", dose: "20mg", type: "Blood Pressure", cost: "₹50", generic: "Nicardia" },
    { name: "Clonidine", dose: "100mcg", type: "Blood Pressure", cost: "₹35", generic: "Catapres" },
    { name: "Methyldopa", dose: "250mg", type: "Blood Pressure (Pregnancy)", cost: "₹120", generic: "Alphadopa" },
    { name: "Isosorbide Mononitrate", dose: "20mg", type: "Angina", cost: "₹60", generic: "Ismo" },
    { name: "Ranolazine", dose: "500mg", type: "Angina", cost: "₹220", generic: "Ranozex" },
    { name: "Ivabradine", dose: "5mg", type: "Heart Rate", cost: "₹180", generic: "Coralan" },
    { name: "Ticagrelor", dose: "90mg", type: "Blood Thinner", cost: "₹850", generic: "Brilinta" },
    { name: "Prasugrel", dose: "10mg", type: "Blood Thinner", cost: "₹340", generic: "Effient" },
    { name: "Tranexamic Acid", dose: "500mg", type: "Bleeding", cost: "₹150", generic: "Pause" },
    { name: "Ethamsylate", dose: "500mg", type: "Bleeding", cost: "₹120", generic: "Sylate" },
    { name: "Progesterone", dose: "200mg", type: "Hormone", cost: "₹350", generic: "Susten" },
    { name: "Estrogen", dose: "2mg", type: "Hormone", cost: "₹210", generic: "Progynova" },
    { name: "Levonorgestrel", dose: "1.5mg", type: "Contraceptive", cost: "₹100", generic: "I-Pill" },
    { name: "Mifepristone", dose: "200mg", type: "Medical Abortion", cost: "₹450", generic: "MTP Pill" },
    { name: "Sildenafil (PAH)", dose: "20mg", type: "Pulmonary Hypertension", cost: "₹380", generic: "Revatio" },
    { name: "Bosentan", dose: "62.5mg", type: "Pulmonary Hypertension", cost: "₹1200", generic: "Lupibose" },
    { name: "Salicylate", dose: "various", type: "Pain Relief", cost: "₹30", generic: "Aspirin" },
    { name: "Ketorolac", dose: "10mg", type: "Strong Pain", cost: "₹75", generic: "Ketorol" },
    { name: "Etoricoxib", dose: "90mg", type: "Arthritis Pain", cost: "₹140", generic: "Nucoxia" },
    { name: "Celecoxib", dose: "200mg", type: "Arthritis Pain", cost: "₹190", generic: "Celcox" },
    { name: "Piroxicam", dose: "20mg", type: "Painful Joints", cost: "₹60", generic: "Dolonex" },
    { name: "Thiocolchicoside", dose: "4mg", type: "Muscle Spasm", cost: "₹180", generic: "Myoril" },
    { name: "Methocarbamol", dose: "500mg", type: "Muscle Spasm", cost: "₹110", generic: "Robaxin" },
    { name: "Baclofen", dose: "10mg", type: "Muscle Spasm", cost: "₹95", generic: "Liofen" },
    { name: "Tofacitinib", dose: "5mg", type: "Rheumatoid Arthritis", cost: "₹850", generic: "Xeljanz" },
    { name: "Methotrexate", dose: "10mg", type: "Arthritis/Psoriasis", cost: "₹180", generic: "Folitrax" },
    { name: "Hydroxychloroquine", dose: "200mg", type: "Autoimmune", cost: "₹160", generic: "HCQS" },
    { name: "Azathioprine", dose: "50mg", type: "Immunosuppressant", cost: "₹190", generic: "Imuran" },
    { name: "Mycophenolate", dose: "500mg", type: "Immunosuppressant", cost: "₹450", generic: "Cellcept" },
    { name: "Tacrolimus", dose: "1mg", type: "Immunosuppressant", cost: "₹650", generic: "Pangraf" }
];

export const INSURANCE_DB = [
    { id: "pmjay", name: "Ayushman Bharat (PM-JAY)", type: "Government", eligibility: ["Income < ₹2L", "BPL/SECC"], benefit: "Free treatment at public/private hospitals.", coverage: "₹5 Lakh / family", premium: "₹0", rating: 4.8 },
    { id: "cghs", name: "CGHS", type: "Government", eligibility: ["Central Govt Employee"], benefit: "Unlimited OPD and IPD care.", coverage: "Unlimited", premium: "Scale-based", rating: 4.5 },
    { id: "esis", name: "ESIC", type: "Government", eligibility: ["Salary < ₹21,000"], benefit: "Sickness, Maternity, Disablement cover.", coverage: "Full medical cover", premium: "3.25% by Employer", rating: 4.3 },
    { id: "star-health-comp", name: "Star Health Comprehensive", type: "Private", eligibility: ["Any age"], benefit: "Air ambulance, No capping.", coverage: "₹10 Lakh - ₹1 Cr", premium: "₹15,000+", rating: 4.2 },
    { id: "care-supreme", name: "Care Supreme", type: "Private", eligibility: ["18Y+"], benefit: "500% bonus, Unlimited recharge.", coverage: "₹7 Lakh - ₹25 Lakh", premium: "₹12,000+", rating: 4.4 },
    { id: "hdfc-secure", name: "HDFC Ergo Optima Secure", type: "Private", eligibility: ["18-65Y"], benefit: "4X coverage from day 1.", coverage: "₹5 Lakh - ₹2 Cr", premium: "₹18,000+", rating: 4.7 },
    { id: "niva-bupa-reassure", name: "Niva Bupa ReAssure", type: "Private", eligibility: ["No limit"], benefit: "ReAssure benefit for same illness.", coverage: "₹5 Lakh - ₹1 Cr", premium: "₹14,000+", rating: 4.6 },
    { id: "icici-lombard-shield", name: "ICICI Lombard Health Shield", type: "Private", eligibility: ["3M - 65Y"], benefit: "Tax benefit, Critical illness add-on.", coverage: "₹5 Lakh - ₹50 Lakh", premium: "₹16,000+", rating: 4.5 },
    { id: "tata-aig-elder", name: "Tata AIG Elder Care", type: "Private", eligibility: ["61Y+"], benefit: "Home care, compassionate travel.", coverage: "₹5 Lakh - ₹15 Lakh", premium: "₹25,000+", rating: 4.1 },
    { id: "sbi-arogya-plus", name: "SBI Arogya Plus", type: "Private", eligibility: ["3M - 65Y"], benefit: "Flat premium, OPD benefit.", coverage: "₹1 Lakh - ₹3 Lakh", premium: "₹8,900", rating: 4.2 },
    { id: "insurance-pmjjby", name: "PMJJBY", type: "Government", eligibility: ["18-50Y", "Bank A/c"], benefit: "Life cover in case of death.", coverage: "₹2 Lakh", premium: "₹436/yr", rating: 4.6 },
    { id: "insurance-pmsby", name: "PMSBY", type: "Government", eligibility: ["18-70Y", "Bank A/c"], benefit: "Accident and disability cover.", coverage: "₹2 Lakh", premium: "₹20/yr", rating: 4.5 },
    { id: "lic-arogya-rakshak", name: "LIC Arogya Rakshak", type: "Government", eligibility: ["18-65Y"], benefit: "Fixed benefit for hospital stays.", coverage: "₹2.5 Lakh+", premium: "Age-based", rating: 4.0 },
    { id: "reliance-health-infinity", name: "Reliance Health Infinity", type: "Private", eligibility: ["No limit"], benefit: "Global cover, Restore benefit.", coverage: "₹3 Lakh - ₹5 Cr", premium: "₹13,000+", rating: 4.3 },
    { id: "kotak-health-premier", name: "Kotak Health Premier", type: "Private", eligibility: ["18Y+"], benefit: "Health checkup, cumulative bonus.", coverage: "₹3 Lakh - ₹25 Lakh", premium: "₹11,000+", rating: 4.2 },
    { id: "aditya-birla-activ-health", name: "Activ Health Platinum", type: "Private", eligibility: ["No limit"], benefit: "100% HealthReturns, chronic management.", coverage: "₹2 Lakh - ₹2 Cr", premium: "₹14,500+", rating: 4.5 },
    { id: "bajaj-allianz-health-guard", name: "Health Guard", type: "Private", eligibility: ["18-65Y"], benefit: "Convalescence benefit, sum insured restoration.", coverage: "₹1.5 Lakh - ₹50 Lakh", premium: "₹10,500+", rating: 4.4 },
    { id: "oriental-insurance-individual", name: "Oriental Individual Mediclaim", type: "Government", eligibility: ["18-65Y"], benefit: "Daily allowance, cost of health check.", coverage: "₹1 Lakh - ₹10 Lakh", premium: "₹7,000+", rating: 4.1 },
    { id: "new-india-assurance-premier", name: "New India Premier Mediclaim", type: "Government", eligibility: ["18-65Y"], benefit: "HIV/AIDS cover, critical illness.", coverage: "₹15 Lakh - ₹1 Cr", premium: "₹22,000+", rating: 4.4 },
    { id: "united-india-uni-criticare", name: "Uni Criticare", type: "Government", eligibility: ["18-65Y"], benefit: "Covers 11 critical illnesses.", coverage: "₹1 Lakh - ₹10 Lakh", premium: "₹5,000+", rating: 4.2 },
    { id: "national-insurance-parivar", name: "National Parivar Mediclaim", type: "Government", eligibility: ["18-65Y"], benefit: "Family floater, maternity benefit.", coverage: "₹6 Lakh - ₹50 Lakh", premium: "₹15,000+", rating: 4.3 },
    { id: "care-freedom", name: "Care Freedom", type: "Private", eligibility: ["No pre-policy checkup"], benefit: "Pre-existing cover after 2 yrs.", coverage: "₹3 Lakh - ₹10 Lakh", premium: "₹18,000+", rating: 4.0 },
    { id: "star-senior-citizens", name: "Senior Citizens Red Carpet", type: "Private", eligibility: ["60-75Y"], benefit: "No medical screening required.", coverage: "₹1 Lakh - ₹25 Lakh", premium: "₹22,000+", rating: 4.2 },
    { id: "hdfc-my-health-suraksha", name: "my:health Suraksha", type: "Private", eligibility: ["No limit"], benefit: "Air ambulance, wellness program.", coverage: "₹3 Lakh - ₹75 Lakh", premium: "₹12,000+", rating: 4.5 },
    { id: "manipal-cigna-pro-health", name: "ManipalCigna ProHealth", type: "Private", eligibility: ["18Y+"], benefit: "Worldwide cover, protection plus.", coverage: "₹2.5 Lakh - ₹100 Lakh", premium: "₹14,000+", rating: 4.4 },
    { id: "zuno-health-shield", name: "Zuno Health Shield", type: "Private", eligibility: ["18-65Y"], benefit: "Pay as you use, lifestyle discount.", coverage: "₹3 Lakh - ₹50 Lakh", premium: "₹9,000+", rating: 4.1 },
    { id: "future-generali-health-total", name: "Health Total", type: "Private", eligibility: ["18Y+"], benefit: "Alternative treatment cover.", coverage: "₹3 Lakh - ₹100 Lakh", premium: "₹11,500+", rating: 4.2 },
    { id: "iffco-tokio-health-protector", name: "Health Protector", type: "Private", eligibility: ["18-65Y"], benefit: "Direct setlement, simple process.", coverage: "₹50k - ₹20 Lakh", premium: "₹6,000+", rating: 4.1 },
    { id: "cholamandalam-ms-healthline", name: "Healthline", type: "Private", eligibility: ["18-65Y"], benefit: "Organ donor expense, dental/spectacles.", coverage: "₹1 Lakh - ₹25 Lakh", premium: "₹8,000+", rating: 4.2 },
    { id: "magma-hdi-one-family", name: "One Family", type: "Private", eligibility: ["18-65Y"], benefit: "Non-medical expenses covered.", coverage: "₹3 Lakh - ₹1 Cr", premium: "₹12,000+", rating: 4.3 },
    { id: "navi-health-insurance", name: "Navi Health Insurance", type: "Private", eligibility: ["18-65Y"], benefit: "100% cashless at any hospital.", coverage: "₹2 Lakh - ₹1 Cr", premium: "₹9,000+", rating: 4.1 },
    { id: "digit-comfort-health", name: "Digit Comfort Health", type: "Private", eligibility: ["No limit"], benefit: "No room rent capping, global cover.", coverage: "₹2 Lakh - ₹1 Cr", premium: "₹10,500+", rating: 4.4 },
    { id: "royal-sundaram-lifeline", name: "Lifeline", type: "Private", eligibility: ["18-65Y"], benefit: "Emergency evacuation, worldwide cover.", coverage: "₹2 Lakh - ₹1.5 Cr", premium: "₹13,500+", rating: 4.1 },
    { id: "liberty-health-connect", name: "Health Connect", type: "Private", eligibility: ["18-65Y"], benefit: "Free look period, tax savings.", coverage: "₹2 Lakh - ₹15 Lakh", premium: "₹9,500+", rating: 4.0 },
    { id: "shriram-general-health", name: "Shriram Mediclaim", type: "Private", eligibility: ["18-65Y"], benefit: "Simple documentation, quick claim.", coverage: "₹1 Lakh - ₹10 Lakh", premium: "₹7,500+", rating: 3.9 },
    { id: "raheja-qbe-health-plus", name: "Health Qube", type: "Private", eligibility: ["18-65Y"], benefit: "OPD cover, diagnostic tests.", coverage: "₹1 Lakh - ₹50 Lakh", premium: "₹8,500+", rating: 4.0 },
    { id: "star-cardiac-care", name: "Cardiac Care Platinum", type: "Private", eligibility: ["For heart patients"], benefit: "Covers heart complications.", coverage: "₹5 Lakh - ₹10 Lakh", premium: "₹35,000+", rating: 4.4 },
    { id: "star-cancer-care", name: "Star Cancer Care Gold", type: "Private", eligibility: ["For cancer patients"], benefit: "Covers recurrence expenses.", coverage: "₹3 Lakh - ₹5 Lakh", premium: "₹45,000+", rating: 4.3 },
    { id: "star-diabetes-safe", name: "Diabetes Safe", type: "Private", eligibility: ["For diabetics"], benefit: "No waiting for diabetic complications.", coverage: "₹3 Lakh - ₹10 Lakh", premium: "₹25,000+", rating: 4.4 },
    { id: "max-bupa-go-active", name: "GoActive", type: "Private", eligibility: ["No limit"], benefit: "Behavioral counseling, home diagnostics.", coverage: "₹4 Lakh - ₹25 Lakh", premium: "₹14,000+", rating: 4.3 },
    { id: "niva-reassure-2-0", name: "ReAssure 2.0", type: "Private", eligibility: ["18Y+"], benefit: "Carry forward unused SI.", coverage: "₹5 Lakh - ₹1 Cr", premium: "₹15,000+", rating: 4.7 },
    { id: "icici-health-booster", name: "Health Booster", type: "Private", eligibility: ["Top-up"], benefit: "High SI at low premium.", coverage: "₹5 Lakh - ₹50 Lakh", premium: "₹3,500+", rating: 4.6 },
    { id: "care-supreme-top-up", name: "Care Enhance", type: "Private", eligibility: ["Top-up"], benefit: "Global coverage available.", coverage: "₹5 Lakh - ₹50 Lakh", premium: "₹2,800+", rating: 4.5 },
    { id: "hdfc-surplus", name: "my:health Medisure Super Top-up", type: "Private", eligibility: ["Top-up"], benefit: "No pre-policy checkup up to 55Y.", coverage: "₹3 Lakh - ₹20 Lakh", premium: "₹4,000+", rating: 4.5 },
    { id: "star-super-surplus", name: "Super Surplus Gold", type: "Private", eligibility: ["Top-up"], benefit: "Delivery expenses covered.", coverage: "₹5 Lakh - ₹100 Lakh", premium: "₹3,200+", rating: 4.4 },
    { id: "oriental-hope", name: "Oriental Happy Family Floater", type: "Government", eligibility: ["Family"], benefit: "TPA services, quick settlement.", coverage: "₹2 Lakh - ₹20 Lakh", premium: "₹12,000+", rating: 4.1 },
    { id: "new-india-global", name: "Global Mediclaim", type: "Government", eligibility: ["18-65Y"], benefit: "World-wide hospitalization cover.", coverage: "$1 Million+", premium: "₹55,000+", rating: 4.5 },
    { id: "national-varta", name: "National Senior Citizen Mediclaim", type: "Government", eligibility: ["60-80Y"], benefit: "Hospitalization & AYUSH.", coverage: "₹1 Lakh - ₹10 Lakh", premium: "₹28,000+", rating: 4.0 },
    { id: "pmsby-accident", name: "Pradhan Mantri Suraksha Bima Yojana", type: "Government", eligibility: ["18-70 years"], benefit: "Death and total disability coverage.", coverage: "₹2 Lakhs", premium: "₹20/year", rating: 4.7 },
    { id: "pmjjby-life", name: "Pradhan Mantri Jeevan Jyoti Bima Yojana", type: "Government", eligibility: ["18-50 years"], benefit: "Life insurance coverage.", coverage: "₹2 Lakhs", premium: "₹436/year", rating: 4.8 },
    // --- 50 New Schemes Added Below ---
    { id: "sbi-general-arogya-topup", name: "SBI Arogya Top Up", type: "Private", eligibility: ["18-65Y"], benefit: "High deductible cover.", coverage: "₹1 Lakh - ₹50 Lakh", premium: "₹2,500+", rating: 4.2 },
    { id: "icici-lombard-complete", name: "ICICI Complete Health", type: "Private", eligibility: ["Adults"], benefit: "Wellness programs included.", coverage: "₹3 Lakh - ₹50 Lakh", premium: "₹11,000+", rating: 4.5 },
    { id: "tata-aig-medicare", name: "Tata AIG Medicare", type: "Private", eligibility: ["No limit"], benefit: "Global cover and maternity benefit.", coverage: "₹5 Lakh - ₹2 Cr", premium: "₹14,500+", rating: 4.6 },
    { id: "star-family-health-optima", name: "Star Family Health Optima", type: "Private", eligibility: ["18-65Y"], benefit: "Automatic restoration of SI.", coverage: "₹3 Lakh - ₹25 Lakh", premium: "₹12,500+", rating: 4.3 },
    { id: "nivabupa-health-premia", name: "Niva Bupa Health Premia", type: "Private", eligibility: ["No limit"], benefit: "International treatment cover.", coverage: "₹5 Lakh - ₹3 Cr", premium: "₹18,000+", rating: 4.5 },
    { id: "care-classic", name: "Care Classic", type: "Private", eligibility: ["Zone based"], benefit: "Zonal pricing structure.", coverage: "₹5 Lakh - ₹15 Lakh", premium: "₹9,000+", rating: 4.1 },
    { id: "hdfc-ergo-optima-restore", name: "HDFC Optima Restore", type: "Private", eligibility: ["adults"], benefit: "Multiplies SI if un-utilized.", coverage: "₹3 Lakh - ₹50 Lakh", premium: "₹13,000+", rating: 4.6 },
    { id: "aditya-birla-activ-assured", name: "Activ Assured", type: "Private", eligibility: ["18-65Y"], benefit: "Health returns and chronic cover.", coverage: "₹5 Lakh - ₹2 Cr", premium: "₹15,000+", rating: 4.4 },
    { id: "kotak-health-care", name: "Kotak Health Care", type: "Private", eligibility: ["Adults"], benefit: "Cashless at vast network.", coverage: "₹2 Lakh - ₹1 Cr", premium: "₹10,500+", rating: 4.2 },
    { id: "magma-hdi-optima", name: "Magma HDI Optima", type: "Private", eligibility: ["18-65Y"], benefit: "No sub-limits on room rent.", coverage: "₹3 Lakh - ₹50 Lakh", premium: "₹11,000+", rating: 4.1 },
    { id: "royal-sundaram-family-plus", name: "Family Plus", type: "Private", eligibility: ["Family"], benefit: "Maternity & newborn coverage.", coverage: "₹3 Lakh - ₹50 Lakh", premium: "₹16,000+", rating: 4.3 },
    { id: "zuno-health-insurance", name: "Zuno Health Policy", type: "Private", eligibility: ["18-65Y"], benefit: "Flexible sum insured options.", coverage: "₹3 Lakh - ₹1 Cr", premium: "₹10,000+", rating: 4.0 },
    { id: "future-generali-health-suraksha", name: "Health Suraksha", type: "Private", eligibility: ["18-65Y"], benefit: "Affordable basic cover.", coverage: "₹1 Lakh - ₹10 Lakh", premium: "₹7,500+", rating: 4.1 },
    { id: "liberty-general-health", name: "Liberty Health", type: "Private", eligibility: ["18-65Y"], benefit: "Auto restore benefit.", coverage: "₹2 Lakh - ₹15 Lakh", premium: "₹9,000+", rating: 4.0 },
    { id: "reliance-health-gain", name: "Reliance Health Gain", type: "Private", eligibility: ["18-65Y"], benefit: "Customizable policies.", coverage: "₹3 Lakh - ₹1 Cr", premium: "₹11,500+", rating: 4.2 },
    { id: "bajaj-allianz-star-package", name: "Health Care Supreme", type: "Private", eligibility: ["Adults"], benefit: "Maternity & OPD expenses.", coverage: "₹5 Lakh - ₹50 Lakh", premium: "₹17,000+", rating: 4.5 },
    { id: "oriental-insurance-happy-family", name: "Happy Family Floater", type: "Government", eligibility: ["Family"], benefit: "Gold/Silver/Diamond plans.", coverage: "₹2 Lakh - ₹20 Lakh", premium: "₹10,500+", rating: 4.2 },
    { id: "national-insurance-mediclaim", name: "National Mediclaim", type: "Government", eligibility: ["18-65Y"], benefit: "Allopathic, Ayurvedic, Homeopathic cover.", coverage: "₹1 Lakh - ₹10 Lakh", premium: "₹8,000+", rating: 4.1 },
    { id: "new-india-assurance-floater", name: "New India Floater", type: "Government", eligibility: ["Family"], benefit: "Covers pre-existing diseases after 4 years.", coverage: "₹2 Lakh - ₹15 Lakh", premium: "₹12,000+", rating: 4.3 },
    { id: "united-india-family-medicare", name: "Family Medicare", type: "Government", eligibility: ["Family"], benefit: "Affordable family protection.", coverage: "₹1 Lakh - ₹10 Lakh", premium: "₹9,500+", rating: 4.0 },
    { id: "navi-health-cure", name: "Navi Cure", type: "Private", eligibility: ["Adults"], benefit: "Paperless digital process.", coverage: "₹2 Lakh - ₹50 Lakh", premium: "₹8,500+", rating: 4.2 },
    { id: "digit-health-care-plus", name: "Digit Health Care Plus", type: "Private", eligibility: ["Adults"], benefit: "Zero co-payment options.", coverage: "₹2 Lakh - ₹1 Cr", premium: "₹10,000+", rating: 4.4 },
    { id: "raheja-qbe-health-insurance", name: "Raheja QBE Health", type: "Private", eligibility: ["18-65Y"], benefit: "Quick approvals.", coverage: "₹1 Lakh - ₹50 Lakh", premium: "₹9,500+", rating: 4.1 },
    { id: "shriram-general-family", name: "Shriram Family Health", type: "Private", eligibility: ["Family"], benefit: "Basic affordable floater.", coverage: "₹2 Lakh - ₹10 Lakh", premium: "₹8,000+", rating: 3.9 },
    { id: "cholamandalam-ms-flexi", name: "Chola Flexi Health", type: "Private", eligibility: ["18-65Y"], benefit: "Daily cash allowance.", coverage: "₹1 Lakh - ₹25 Lakh", premium: "₹8,500+", rating: 4.1 },
    { id: "iffco-tokio-family-protector", name: "Family Protector", type: "Private", eligibility: ["Family"], benefit: "Vaccination cover.", coverage: "₹1.5 Lakh - ₹30 Lakh", premium: "₹9,500+", rating: 4.2 },
    { id: "star-health-gain", name: "Star Health Gain", type: "Private", eligibility: ["18-65Y"], benefit: "Outpatient expenses cover.", coverage: "₹1 Lakh - ₹5 Lakh", premium: "₹8,000+", rating: 4.1 },
    { id: "care-advantage", name: "Care Advantage", type: "Private", eligibility: ["Adults"], benefit: "High SI up to 1Cr.", coverage: "₹25 Lakh - ₹1 Cr", premium: "₹15,000+", rating: 4.5 },
    { id: "niva-bupa-heartbeat", name: "Heartbeat", type: "Private", eligibility: ["Couples/Families"], benefit: "Maternity cover from day 1.", coverage: "₹5 Lakh - ₹1 Cr", premium: "₹22,000+", rating: 4.4 },
    { id: "icici-lombard-maxprotect", name: "MaxProtect", type: "Private", eligibility: ["Adults"], benefit: "Comprehensive global cover.", coverage: "₹1 Cr+", premium: "₹35,000+", rating: 4.6 },
    { id: "hdfc-ergo-health-suraksha", name: "Health Suraksha Gold", type: "Private", eligibility: ["Adults"], benefit: "No room rent capping.", coverage: "₹3 Lakh - ₹10 Lakh", premium: "₹10,500+", rating: 4.3 },
    { id: "sbi-general-retail-health", name: "Retail Health", type: "Private", eligibility: ["18-65Y"], benefit: "Add-on covers available.", coverage: "₹1 Lakh - ₹5 Lakh", premium: "₹7,000+", rating: 4.0 },
    { id: "bajaj-allianz-tax-gain", name: "Tax Gain", type: "Private", eligibility: ["Adults"], benefit: "Specific OPD limits.", coverage: "₹1 Lakh - ₹3 Lakh", premium: "₹6,000+", rating: 4.1 },
    { id: "tata-aig-medicare-premier", name: "Medicare Premier", type: "Private", eligibility: ["Adults"], benefit: "High end OPD care.", coverage: "₹5 Lakh - ₹3 Cr", premium: "₹20,000+", rating: 4.7 },
    { id: "care-heart", name: "Care Heart", type: "Private", eligibility: ["Cardiac Patients"], benefit: "For pre-existing heart ailments.", coverage: "₹3 Lakh - ₹10 Lakh", premium: "₹28,000+", rating: 4.3 },
    { id: "star-diabetes-safe-plus", name: "Diabetes Safe Plus", type: "Private", eligibility: ["Diabetics"], benefit: "Covers Type 1 and Type 2.", coverage: "₹3 Lakh - ₹10 Lakh", premium: "₹26,000+", rating: 4.4 },
    { id: "aditya-birla-activ-care", name: "Activ Care Senior", type: "Private", eligibility: ["60Y+"], benefit: "Specialized senior citizen plan.", coverage: "₹3 Lakh - ₹25 Lakh", premium: "₹25,000+", rating: 4.2 },
    { id: "niva-bupa-senior-first", name: "Senior First", type: "Private", eligibility: ["61Y+"], benefit: "No pre-policy medical check.", coverage: "₹5 Lakh - ₹25 Lakh", premium: "₹28,000+", rating: 4.3 },
    { id: "icici-lombard-golden-shield", name: "Golden Shield", type: "Private", eligibility: ["60Y+"], benefit: "Critical illness for seniors.", coverage: "₹5 Lakh - ₹20 Lakh", premium: "₹30,000+", rating: 4.2 },
    { id: "care-senior", name: "Care Senior", type: "Private", eligibility: ["61Y+"], benefit: "AYUSH treatment cover.", coverage: "₹3 Lakh - ₹10 Lakh", premium: "₹24,000+", rating: 4.1 },
    { id: "hdfc-ergo-optima-senior", name: "Optima Senior", type: "Private", eligibility: ["61Y+"], benefit: "Cashless home healthcare.", coverage: "₹2 Lakh - ₹5 Lakh", premium: "₹22,000+", rating: 4.2 },
    { id: "star-special-care", name: "Special Care (Austism)", type: "Private", eligibility: ["Autism Patients"], benefit: "Specialized therapies cover.", coverage: "₹3 Lakh", premium: "₹15,000+", rating: 4.6 },
    { id: "nivabupa-criti-care", name: "CritiCare", type: "Private", eligibility: ["Adults"], benefit: "Lump sum payout on 20 illnesses.", coverage: "₹5 Lakh - ₹2 Cr", premium: "₹5,000+ (Term)", rating: 4.5 },
    { id: "icici-lombard-criti-shield", name: "CritiShield", type: "Private", eligibility: ["Adults"], benefit: "Cardiac and Cancer special cover.", coverage: "₹5 Lakh - ₹50 Lakh", premium: "₹6,500+", rating: 4.4 },
    { id: "care-cancer", name: "Care Cancer", type: "Private", eligibility: ["Adults"], benefit: "Indemnity and Benefit cover.", coverage: "₹10 Lakh - ₹2 Cr", premium: "₹12,000+", rating: 4.6 },
    { id: "sbi-critical-illness", name: "SBI Critical Illness", type: "Private", eligibility: ["18-65Y"], benefit: "Covers 13 critical ailments.", coverage: "₹2 Lakh - ₹50 Lakh", premium: "₹4,000+", rating: 4.3 },
    { id: "tata-aig-criti-medicare", name: "Criti Medicare", type: "Private", eligibility: ["Adults"], benefit: "100+ critical illnesses.", coverage: "₹5 Lakh - ₹2 Cr", premium: "₹8,000+", rating: 4.7 },
    { id: "aditya-birla-criti-secure", name: "Criti Secure", type: "Private", eligibility: ["18-65Y"], benefit: "Survival period of 15 days.", coverage: "₹5 Lakh - ₹1 Cr", premium: "₹6,000+", rating: 4.5 },
    { id: "bajaj-allianz-criti-care", name: "CritiCare", type: "Private", eligibility: ["Adults"], benefit: "Donor expenses covered.", coverage: "₹1 Lakh - ₹50 Lakh", premium: "₹5,500+", rating: 4.4 },
    { id: "future-generali-criti-care", name: "Criti Care", type: "Private", eligibility: ["18-65Y"], benefit: "Lumpsum payment.", coverage: "₹1 Lakh - ₹50 Lakh", premium: "₹5,000+", rating: 4.2 }
];
